// Auth
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const SIGNUP = "SIGNUP";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const USERNAME_EXISTS = "USERNAME_EXISTS";
export const FILL_USERNAME_EXISTS = "FILL_USERNAME_EXISTS";
export const CLEAR_USERNAME_EXISTS = "CLEAR_USERNAME_EXISTS";
export const EMAIL_EXISTS = "EMAIL_EXISTS";
export const FILL_EMAIL_EXISTS = "FILL_EMAIL_EXISTS";
export const CLEAR_EMAIL_EXISTS = "CLEAR_EMAIL_EXISTS";
export const CLEAR_SIGNUP_ERROR = "CLEAR_SIGNUP_ERROR";
export const CLEAR_LOGIN_ERROR = "CLEAR_LOGIN_ERROR";
export const CLEAR_SIGNUP_SUCCESS = "CLEAR_SIGNUP_SUCCESS";

//snack bar
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
